services:
  umbraco:
    # build:
    #   context: .
    image: ghcr.io/emilstorgaard/elines-krudtugler-umbraco:latest
    container_name: elines-krudtugler-umbraco
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__umbracoDbDSN=Server=elineskrudtugler.dk,1433;Database=ElinesKrudtuglerUmbracoDB;User Id=DITBRUGERNAVN;Password=DITPASSWORD;TrustServerCertificate=true;
      - ConnectionStrings__umbracoDbDSN_ProviderName=Microsoft.Data.SqlClient
    ports:
      - "8580:8080"
    volumes:
      - umbraco-media:/app/wwwroot/media
      - umbraco-logs:/app/umbraco/Logs
    networks:
      - mssql-network

networks:
  mssql-network:
    external: true
    name: mssql_default

volumes:
  umbraco-media:
  umbraco-logs: