//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.3.5+1486121
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Praktisk</summary>
	[PublishedModel("practicalPage")]
	public partial class PracticalPage : PublishedContentModel, ISeo
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		public new const string ModelTypeAlias = "practicalPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<PracticalPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public PracticalPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Banner ikon: Emoji der vises i banneret. Fx ✅.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("approvalBannerIcon")]
		public virtual string ApprovalBannerIcon => this.Value<string>(_publishedValueFallback, "approvalBannerIcon");

		///<summary>
		/// Banner undertitel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("approvalBannerSubtitle")]
		public virtual string ApprovalBannerSubtitle => this.Value<string>(_publishedValueFallback, "approvalBannerSubtitle");

		///<summary>
		/// Banner titel: Fed tekst i banneret. Fx 'Godkendt af Viborg Kommune'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("approvalBannerTitle")]
		public virtual string ApprovalBannerTitle => this.Value<string>(_publishedValueFallback, "approvalBannerTitle");

		///<summary>
		/// Info kort
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("approvalCards")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel ApprovalCards => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "approvalCards");

		///<summary>
		/// Sektion label: Vises som badge. Fx 'Godkendelse og tilsyn'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("approvalLabel")]
		public virtual string ApprovalLabel => this.Value<string>(_publishedValueFallback, "approvalLabel");

		///<summary>
		/// Elines liste
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringElineItems")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel BringElineItems => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "bringElineItems");

		///<summary>
		/// Elines liste – titel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringElineTitle")]
		public virtual string BringElineTitle => this.Value<string>(_publishedValueFallback, "bringElineTitle");

		///<summary>
		/// Sektion intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringIntro")]
		public virtual string BringIntro => this.Value<string>(_publishedValueFallback, "bringIntro");

		///<summary>
		/// Sektion label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringLabel")]
		public virtual string BringLabel => this.Value<string>(_publishedValueFallback, "bringLabel");

		///<summary>
		/// Forældrenes liste
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringParentsItems")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel BringParentsItems => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "bringParentsItems");

		///<summary>
		/// Forældrenes liste – titel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bringParentsTitle")]
		public virtual string BringParentsTitle => this.Value<string>(_publishedValueFallback, "bringParentsTitle");

		///<summary>
		/// Sektion label: Vises som badge. Fx 'Kost'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dietLabel")]
		public virtual string DietLabel => this.Value<string>(_publishedValueFallback, "dietLabel");

		///<summary>
		/// Slut bemærkning: Afsluttende bemærkning i kursiv.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysClosingNote")]
		public virtual string HolidaysClosingNote => this.Value<string>(_publishedValueFallback, "holidaysClosingNote");

		///<summary>
		/// Fremhævet besked: Vises i farvet boks – hovedinfo om varslingstidspunkt.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysHighlight")]
		public virtual string HolidaysHighlight => this.Value<string>(_publishedValueFallback, "holidaysHighlight");

		///<summary>
		/// Fremhævet besked (under): Vises under hovedinfoen i samme boks.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysHighlightSub")]
		public virtual string HolidaysHighlightSub => this.Value<string>(_publishedValueFallback, "holidaysHighlightSub");

		///<summary>
		/// Intro tekst: Første afsnit med generel info om ferie og lukkedage.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysIntro")]
		public virtual string HolidaysIntro => this.Value<string>(_publishedValueFallback, "holidaysIntro");

		///<summary>
		/// Sektion label: Vises som badge øverst. Fx 'Ferie og lukkedage'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysLabel")]
		public virtual string HolidaysLabel => this.Value<string>(_publishedValueFallback, "holidaysLabel");

		///<summary>
		/// Ferie statement: Fremhævet udsagn om feriens omfang. Fx 'Jeg holder 6 ugers ferie om året.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("holidaysStatement")]
		public virtual string HolidaysStatement => this.Value<string>(_publishedValueFallback, "holidaysStatement");

		///<summary>
		/// Åbningstider: Lille note under tabellen. Fx 'Special aftale kan laves'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openingHours")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel OpeningHours => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "openingHours");

		///<summary>
		/// Sektion label: Vises som badge over åbningstiderne. Fx 'Krudtuglernes åbningstider'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openingHoursLabel")]
		public virtual string OpeningHoursLabel => this.Value<string>(_publishedValueFallback, "openingHoursLabel");

		///<summary>
		/// Tilføjelse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("openingHoursNote")]
		public virtual string OpeningHoursNote => this.Value<string>(_publishedValueFallback, "openingHoursNote");

		///<summary>
		/// Sidetitel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Slut bemærkning: Afsluttende bemærkning i kursiv.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("parentCoopClosingNote")]
		public virtual string ParentCoopClosingNote => this.Value<string>(_publishedValueFallback, "parentCoopClosingNote");

		///<summary>
		/// Fremhævet boks: Vises i farvet fremhævet boks.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("parentCoopHighlight")]
		public virtual string ParentCoopHighlight => this.Value<string>(_publishedValueFallback, "parentCoopHighlight");

		///<summary>
		/// Sektion label: Vises som badge. Fx 'Forældresamarbejde'.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("parentCoopLabel")]
		public virtual string ParentCoopLabel => this.Value<string>(_publishedValueFallback, "parentCoopLabel");

		///<summary>
		/// Hovedtekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("parentCoopMainText")]
		public virtual string ParentCoopMainText => this.Value<string>(_publishedValueFallback, "parentCoopMainText");

		///<summary>
		/// Mellem-tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("parentCoopMiddleText")]
		public virtual string ParentCoopMiddleText => this.Value<string>(_publishedValueFallback, "parentCoopMiddleText");

		///<summary>
		/// Tilskud-titel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingDiscountLabel")]
		public virtual string PricingDiscountLabel => this.Value<string>(_publishedValueFallback, "pricingDiscountLabel");

		///<summary>
		/// Tilskud-værdi: Negativt tal med minus foran. Fx '− 7.176 kr.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingDiscountValue")]
		public virtual string PricingDiscountValue => this.Value<string>(_publishedValueFallback, "pricingDiscountValue");

		///<summary>
		/// Egenbetaling-label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingFinalLabel")]
		public virtual string PricingFinalLabel => this.Value<string>(_publishedValueFallback, "pricingFinalLabel");

		///<summary>
		/// Egenbetaling-enhed: Enhed der vises i lille tekst. Fx 'kr./md.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingFinalUnit")]
		public virtual string PricingFinalUnit => this.Value<string>(_publishedValueFallback, "pricingFinalUnit");

		///<summary>
		/// Egenbetaling-værdi: Slutpris uden enhed. Fx '2.900'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingFinalValue")]
		public virtual string PricingFinalValue => this.Value<string>(_publishedValueFallback, "pricingFinalValue");

		///<summary>
		/// Info tiles
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingInfoTiles")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel PricingInfoTiles => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "pricingInfoTiles");

		///<summary>
		/// Sektion intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingIntro")]
		public virtual string PricingIntro => this.Value<string>(_publishedValueFallback, "pricingIntro");

		///<summary>
		/// Sektion label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingLabel")]
		public virtual string PricingLabel => this.Value<string>(_publishedValueFallback, "pricingLabel");

		///<summary>
		/// Pris-titel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingPriceLabel")]
		public virtual string PricingPriceLabel => this.Value<string>(_publishedValueFallback, "pricingPriceLabel");

		///<summary>
		/// Pris-værdi: Fx '10.176 kr.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingPriceValue")]
		public virtual string PricingPriceValue => this.Value<string>(_publishedValueFallback, "pricingPriceValue");

		///<summary>
		/// Sub info tiles
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pricingSubTiles")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel PricingSubTiles => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "pricingSubTiles");

		///<summary>
		/// Meta beskrivelse: Vises som beskrivelse i Google's søgeresultater. Anbefalet 150-160 tegn.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Meta titel: Vises i Google's søgeresultater og browser-fanen. Anbefalet 50-60 tegn.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTitle")]
		public virtual string MetaTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetMetaTitle(this, _publishedValueFallback);

		///<summary>
		/// OG billede: Valgfri: Billede der vises når siden deles på Facebook eller LinkedIn. Anbefalet 1200x630px.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.3.5+1486121")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogImage")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops> OgImage => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetOgImage(this, _publishedValueFallback);
	}
}
